### ISSUE TITLE
[styling] Front IOS common style setup

### ISSUE THREAD

**Issue by 77unny** [codesquad-memeber-2020/signup-4#16]
### color code 
- default color : #252525
- CI color : #00c84f
- error color : #e65f3e
- gray color : #f2f4f7

### font size (web / px 단위)
- default : 14px
- smal : 12px
- large : 16px
- extra : 18px

### font family (web)
- default : "Noto Sans KR", "AppleSDGothicNeo-Regular", "맑은 고딕",
  "Malgun Gothic", "돋움", "dotum" sans-serif;

@Limwin94 참고부탁드려용! 
web front는 네이버 로그인 기준하에 정의 하였습니다.

**Comment by Limwin94** [comment]
default, small, large, extra는 각각 어디에 적용하나요?

>> 아..xd에 있네요 ㅠㅠ

**Comment by 77unny** [comment]
> default, small, large, extra는 각각 어디에 적용하나요?
> 
> > > 아..xd에 있네요 ㅠㅠ

font-size 는 web이라 크게 비중안두셔도 될꺼같아요 ㅎㅎ 디자인파일이 별도로 없어서 눈에보이는게 괜찮다면 넘어가면 될꺼같아요 ㅎㅎ
