### ISSUE TITLE
JSON serialize/deseralize 적용을 위한 Jackson 라이브러리 적용

### ISSUE THREAD

**Issue by sigridjineth** [codesquad-memeber-2020/signup-4#21]
API 사용을 위해 프론트/iOS 간의 원활한 통신을 위한 JSON 변환 라이브러리 사용을 익힙니다.
현재 User 클래스 생성 시에 interest를 어떻게 처리해야 할 지 이야기를 나눠야 합니다.

**Comment by realsigridjin** [comment]
jackson은 이미 스프링 부트에 있고 @RestController 어노테이션을 사용해서 POJO 클래스를 리턴하면 된다고 함
