### ISSUE TITLE
API 문서화 방법 리서치 

### ISSUE THREAD

**Issue by bohyeon-n** [codesquad-memeber-2020/signup-4#7]
API 문서화 하는 방법 결정하기 

##  후보 
- Spring Restdocs 
- Spring fox

**Comment by bohyeon-n** [comment]
@jypthemiracle  문서화 하면 좋을 것 같은데 어떤 방법 쓰는게 좋을까요?

**Comment by realsigridjin** [comment]
@bohyeon-n 다른 팀의 Jack이 Swagger를 소대해주었어요. 자바 진영에서 많이 사용하는 API 문서화 툴이라고 하네요. 학습하고 적용해보겠습니다.

**Comment by bohyeon-n** [comment]
@jypthemiracle  그럼 Swagger 적용 후 알려주세요~ ! 이 이슈는 중복되는 것 같으니 닫겠습니다 :)
