### ISSUE TITLE
로그인 방법 결정 

### ISSUE THREAD

**Issue by bohyeon-n** [codesquad-memeber-2020/signup-4#8]
로그인 상태 유지 시키는 방법을 어떤 걸로 하면 좋을지 공부하고 결정하기

**Comment by realsigridjin** [comment]
제가 로그인 담당이니까 조금 리서치하고 이야기를 나누면 좋을 것 같습니다.

**Comment by realsigridjin** [comment]
이번 기회에 스프링 시큐리티를 적용해보면 좋을 것 같습니다. 어떻게 생각하시나요? 너무 무거울까요?

**Comment by jypthemiracle** [comment]
이번 기회에 스프링 시큐리티를 적용해보면 좋을 것 같다고 적었는데요. 너무 과할 것 같아서 일단 httpSession.setAttribute로 진행하고 시간이 남으면 리팩토링하면서 학습해보는 것으로 하겠습니다. 의견 남겨주세요.

**Comment by realsigridjin** [comment]
스프링 시큐리티는 찾아보니 너무 과할 것 같다는 생각이 들어서 일단 ```httpSession.setAttribute()```로 진행하고 시간이 남으면 리팩토링하면서 학습해보는 것으로 하겠습니다. 의견 남겨주세요.

**Comment by bohyeon-n** [comment]
넵 좋아요! 일단 아는 걸로 구현하고 나중에 바꿔보는 것도 좋을 것 같습니다!
